### ISSUE TITLE
No .keypirinha-package file

### ISSUE THREAD

**Issue by ueffel** [PatrickThVillanueva/keypirinha-reddit#1]
Can you add a ready to use .keypirinha-package in the release section to ease manual installing and make it possible for PackageControl to pick it up?

There is actually no need to commit the .keypirinha-package file in the repository itself. Not in a `build/` directory, not in a `/release` directory, not anywhere :)

**Comment by sharkoz** [comment]
I opened #2 to automatically deploy the release through Github actions

**Comment by PatrickThVillanueva** [comment]
> Can you add a ready to use .keypirinha-package in the release section to ease manual installing and make it possible for PackageControl to pick it up?
> 
> There is actually no need to commit the .keypirinha-package file in the repository itself. Not in a `build/` directory, not in a `/release` directory, not anywhere :)

Yes! Absolutely - with the help of @sharkoz this has been fixed!
https://github.com/PatrickThVillanueva/keypirinha-reddit/releases

Thank you for your contributions

**Comment by ueffel** [comment]
There is still no `*.keypirinha-package` asset in the release. 🤔

**Comment by PatrickThVillanueva** [comment]
Sorry - I am still new to GitHub releases.
I hope this lates update helped.
https://github.com/PatrickThVillanueva/keypirinha-reddit/releases/tag/v1.1

**Comment by ueffel** [comment]
that one looks better.

**Comment by sharkoz** [comment]
I updated my PR to actually include the package in #3

**Comment by PatrickThVillanueva** [comment]
Thank you guys :D
